[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
